config/routes.rb
Rails.application.routes.draw do
  get '/brew_types/new',      :controller => 'brew_types', :action => 'new',    :as => 'new_brew_type'
  post '/brew_types',         :controller => 'brew_types', :action => 'create', :as => 'brew_types'

  get '/brew_types',          :controller => 'brew_types', :action => 'index'
  get '/brew_types/:id',      :controller => 'brew_types', :action => 'show',   :as => 'brew_type'

  get '/brew_types/:id/edit', :controller => 'brew_types', :action => 'edit',   :as => 'edit_brew_type'
  patch '/brew_types/:id',    :controller => 'brew_types', :action => 'update'

  delete '/brew_types/:id',   :controller => 'brew_types', :action => 'destroy'

  get '/brews/new',      :controller => 'brews', :action => 'new',    :as => 'new_brew'
  post '/brews',         :controller => 'brews', :action => 'create', :as => 'brews'

  get '/brews',          :controller => 'brews', :action => 'index'
  get '/brews/:id',      :controller => 'brews', :action => 'show',   :as => 'brew'

  get '/brews/:id/edit', :controller => 'brews', :action => 'edit',   :as => 'edit_brew'
  patch '/brews/:id',    :controller => 'brews', :action => 'update'

  delete '/brews/:id',   :controller => 'brews', :action => 'destroy'

  get '/standards/new',      :controller => 'standards', :action => 'new',    :as => 'new_standard'
  post '/standards',         :controller => 'standards', :action => 'create', :as => 'standards'

  get '/standards',          :controller => 'standards', :action => 'index'
  get '/standards/:id',      :controller => 'standards', :action => 'show',   :as => 'standard'

  get '/standards/:id/edit', :controller => 'standards', :action => 'edit',   :as => 'edit_standard'
  patch '/standards/:id',    :controller => 'standards', :action => 'update'

  delete '/standards/:id',   :controller => 'standards', :action => 'destroy'

  get '/batches/new',      :controller => 'batches', :action => 'new',    :as => 'new_batch'
  post '/batches',         :controller => 'batches', :action => 'create', :as => 'batches'

  get '/batches',          :controller => 'batches', :action => 'index'
  get '/batches/:id',      :controller => 'batches', :action => 'show',   :as => 'batch'

  get '/batches/:id/edit', :controller => 'batches', :action => 'edit',   :as => 'edit_batch'
  patch '/batches/:id',    :controller => 'batches', :action => 'update'

  delete '/batches/:id',   :controller => 'batches', :action => 'destroy'

  get '/reviews/new',      :controller => 'reviews', :action => 'new',    :as => 'new_review'
  post '/reviews',         :controller => 'reviews', :action => 'create', :as => 'reviews'

  get '/reviews',          :controller => 'reviews', :action => 'index'
  get '/reviews/:id',      :controller => 'reviews', :action => 'show',   :as => 'review'

  get '/reviews/:id/edit', :controller => 'reviews', :action => 'edit',   :as => 'edit_review'
  patch '/reviews/:id',    :controller => 'reviews', :action => 'update'

  delete '/reviews/:id',   :controller => 'reviews', :action => 'destroy'

end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new
    @review.like = params[:like]
    @review.rating = params[:rating]
    @review.desc = params[:desc]
    @review.brew_id = params[:brew_id]
    @review.batch_id = params[:batch_id]
    @review.user_id = params[:user_id]

    if @review.save
      redirect_to reviews_url, :notice => "Review created successfully."
    else
      render 'new'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    @review.like = params[:like]
    @review.rating = params[:rating]
    @review.desc = params[:desc]
    @review.brew_id = params[:brew_id]
    @review.batch_id = params[:batch_id]
    @review.user_id = params[:user_id]

    if @review.save
      redirect_to review_url(@review.id), :notice => "Review updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @review = Review.find(params[:id])

    @review.destroy

    redirect_to reviews_url, :notice => "Review deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>TheBrewersEdge</title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.0/slate/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">TheBrewersEdge</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/brew_types">Brew Types</a></li>
        <li><a href="/brews">Brews</a></li>
        <li><a href="/standards">Standards</a></li>
        <li><a href="/batches">Batches</a></li>
        <li><a href="/reviews">Reviews</a></li>
        <li><a href="#">About</a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if 1 > 2 %>
          <li><a href="/users/edit">Oscar the Grouch</a></li>
          <li><a href="/users/sign_out" data-method="delete">Sign out</a></li>
        <% else %>
          <li><a href="/users/sign_up">Sign up</a></li>
          <li><a href="/users/sign_in">Sign in</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/reviews/edit.html.erb
<!-- Validation failure messages -->

<% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Review #<%= @review.id %></h3>
      </div>
      <div class="panel-body">
        <%= form_tag review_url(@review.id), :method => "patch", :class => "form-horizontal" do %>
          <!-- Label and input for like -->
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label for="like">
                  <input type="checkbox" id="like" name="like" value="1" <%= "checked" if @review.like %>>
                  Like
                </label>
              </div>
            </div>
          </div>

          <!-- Label and input for rating -->
          <div class="form-group">
            <label for="rating" class="col-sm-2 control-label">
              Rating
            </label>
            <div class="col-sm-10">
              <input type="text" id="rating" name="rating" placeholder="Rating" class="form-control" value="<%= @review.rating %>">
            </div>
          </div>

          <!-- Label and input for desc -->
          <div class="form-group">
            <label for="desc" class="col-sm-2 control-label">
              Desc
            </label>
            <div class="col-sm-10">
              <textarea id="desc" name="desc" placeholder="Desc" class="form-control" rows="3"><%= @review.desc %></textarea>
            </div>
          </div>

          <!-- Label and input for brew_id -->
          <div class="form-group">
            <label for="brew_id" class="col-sm-2 control-label">
              Brew
            </label>
            <div class="col-sm-10">
              <input type="text" id="brew_id" name="brew_id" placeholder="Brew" class="form-control" value="<%= @review.brew_id %>">
            </div>
          </div>

          <!-- Label and input for batch_id -->
          <div class="form-group">
            <label for="batch_id" class="col-sm-2 control-label">
              Batch
            </label>
            <div class="col-sm-10">
              <input type="text" id="batch_id" name="batch_id" placeholder="Batch" class="form-control" value="<%= @review.batch_id %>">
            </div>
          </div>

          <!-- Label and input for user_id -->
          <div class="form-group">
            <label for="user_id" class="col-sm-2 control-label">
              User
            </label>
            <div class="col-sm-10">
              <input type="text" id="user_id" name="user_id" placeholder="User" class="form-control" value="<%= @review.user_id %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Update Review" class="btn btn-warning">
              or
              <%= link_to "Cancel", review_url(@review.id) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- End responsive panel example -->

app/views/reviews/index.html.erb
<div class="page-header">
  <h1>
    Reviews
    <%= link_to new_review_url, :class => "btn btn-lg btn-success" do %>
      <i class="fa fa-plus"></i>
    <% end  %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Reviews (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @reviews.each do |review| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Review #<%= review.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Like</dt>
          <dd><%= review.like %></dd>

          <dt>Rating</dt>
          <dd><%= review.rating %></dd>

          <dt>Desc</dt>
          <dd><%= review.desc %></dd>

          <dt>Brew</dt>
          <dd><%= review.brew_id %></dd>

          <dt>Batch</dt>
          <dd><%= review.batch_id %></dd>

          <dt>User</dt>
          <dd><%= review.user_id %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to review_url(review), :class => "btn btn-primary" do %>
            <i class="fa fa-search-plus"></i>
          <% end %>
          <%= link_to edit_review_url(review), :class => "btn btn-warning" do %>
            <i class="fa fa-edit"></i>
          <% end %>
          <%= link_to review_url(review), :method => "delete", :data => { :confirm => "Do you really want to delete this review?" }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/reviews/new.html.erb
<!-- Validation failure messages -->

<% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Responsive panel example -->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Add Review</h3>
      </div>
      <div class="panel-body">
        <%= form_tag reviews_url, :method => "post", :class => "form-horizontal" do %>
          <!-- Label and input for like -->
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label for="like">
                  <input type="checkbox" id="like" name="like" value="1" <%= "checked" if @review.like %>>
                  Like
                </label>
              </div>
            </div>
          </div>

          <!-- Label and input for rating -->
          <div class="form-group">
            <label for="rating" class="col-sm-2 control-label">
              Rating
            </label>
            <div class="col-sm-10">
              <input type="text" id="rating" name="rating" placeholder="Rating" class="form-control" value="<%= @review.rating %>">
            </div>
          </div>

          <!-- Label and input for desc -->
          <div class="form-group">
            <label for="desc" class="col-sm-2 control-label">
              Desc
            </label>
            <div class="col-sm-10">
              <textarea id="desc" name="desc" placeholder="Desc" class="form-control" rows="3"><%= @review.desc %></textarea>
            </div>
          </div>

          <!-- Label and input for brew_id -->
          <div class="form-group">
            <label for="brew_id" class="col-sm-2 control-label">
              Brew
            </label>
            <div class="col-sm-10">
              <input type="text" id="brew_id" name="brew_id" placeholder="Brew" class="form-control" value="<%= @review.brew_id %>">
            </div>
          </div>

          <!-- Label and input for batch_id -->
          <div class="form-group">
            <label for="batch_id" class="col-sm-2 control-label">
              Batch
            </label>
            <div class="col-sm-10">
              <input type="text" id="batch_id" name="batch_id" placeholder="Batch" class="form-control" value="<%= @review.batch_id %>">
            </div>
          </div>

          <!-- Label and input for user_id -->
          <div class="form-group">
            <label for="user_id" class="col-sm-2 control-label">
              User
            </label>
            <div class="col-sm-10">
              <input type="text" id="user_id" name="user_id" placeholder="User" class="form-control" value="<%= @review.user_id %>">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <input type="submit" value="Create Review" class="btn btn-success">
              or
              <a href="/reviews">Cancel</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->

app/views/reviews/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Review #<%= @review.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Like</dt>
              <dd><%= @review.like %></dd>

              <dt>Rating</dt>
              <dd><%= @review.rating %></dd>

              <dt>Desc</dt>
              <dd><%= @review.desc %></dd>

              <dt>Brew</dt>
              <dd><%= @review.brew_id %></dd>

              <dt>Batch</dt>
              <dd><%= @review.batch_id %></dd>

              <dt>User</dt>
              <dd><%= @review.user_id %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to reviews_url, :class => "btn btn-primary" do %>
                <i class="fa fa-chevron-left"></i>
              <% end %>
              <%= link_to edit_review_url(@review.id), :class => "btn btn-warning" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <%= link_to review_url(@review.id), :method => "delete", :data => { :confirm => "Do you really want to delete this review?" }, :class => "btn btn-danger" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->